# Generated by Django 4.2.5 on 2023-10-13 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeactions', '0002_floor_actionstore_datestore_actionstore_storenumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionstore',
            name='datestore',
        ),
        migrations.RemoveField(
            model_name='actionstore',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='actionstore',
            name='storenumber',
        ),
        migrations.RemoveField(
            model_name='actionstore',
            name='timestore',
        ),
    ]
